# fly.toml app configuration file generated for damp-wind-6845 on 2023-09-06T19:24:31-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "damp-wind-6845"
primary_region = "den"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[deploy]
  release_command = "npm run migrate up"